#!/usr/bin/env python3
"""Merge src/i18n/*.json into src/i18n.js (window.EBNA_I18N bundle).

en.json is canonical. Every other language inherits English for any missing key
(the runtime t() also falls back to English, so the UI is never under-translated).
Language display names live in NAMES below.
"""
import json, pathlib

root = pathlib.Path(__file__).parent
i18n_dir = root / "src" / "i18n"

NAMES = {
    "en": "English", "it": "Italiano", "de": "Deutsch", "fr": "Français",
    "es": "Español", "pt": "Português", "nl": "Nederlands", "pl": "Polski",
    "ro": "Română", "el": "Ελληνικά", "bg": "Български", "cs": "Čeština",
    "da": "Dansk", "fi": "Suomi", "hr": "Hrvatski", "hu": "Magyar",
    "lt": "Lietuvių", "lv": "Latviešu", "mt": "Malti", "ga": "Gaeilge",
    "sk": "Slovenčina", "sl": "Slovenščina", "sv": "Svenska", "et": "Eesti",
}

en = json.loads((i18n_dir / "en.json").read_text(encoding="utf-8"))
en_keys = [k for k in en.keys() if k != "_meta"]

bundle = {}
# English first (canonical)
en_clean = {k: v for k, v in en.items() if k != "_meta"}
bundle["en"] = {"_meta": {"lang": "en", "name": NAMES["en"], "status": "complete", "canonical": True}}
bundle["en"].update(en_clean)

stats = {}
for path in sorted(i18n_dir.glob("*.json")):
    code = path.stem
    if code == "en":
        continue
    data = json.loads(path.read_text(encoding="utf-8"))
    translated = {k: v for k, v in data.items() if k != "_meta" and v is not None}
    covered = sum(1 for k in en_keys if k in translated)
    declared = (data.get("_meta") or {}).get("status")
    if covered >= len(en_keys):
        # A language may opt into "provisional" (fully translated but the legal
        # terminology is not yet verified against EUR-Lex / a native speaker).
        status = "provisional" if declared == "provisional" else "complete"
    else:
        status = "partial"
    meta = {
        "lang": code,
        "name": NAMES.get(code, code),
        "status": status,
        "canonical": False,
        "note": "Legal terminology from official GDPR translations (EUR-Lex); template-specific labels unofficial pending native review.",
    }
    entry = {"_meta": meta}
    entry.update(translated)
    bundle[code] = entry
    stats[code] = (covered, len(en_keys))

out = "// Auto-generated by build-i18n.py - 24 EU languages.\n"
out += "// GDPR legal terms from EUR-Lex official translations; template labels unofficial pending native review.\n"
out += "window.EBNA_I18N = " + json.dumps(bundle, ensure_ascii=False) + ";\n"
(root / "src" / "i18n.js").write_text(out, encoding="utf-8")

print(f"src/i18n.js written: {len(bundle)} languages, {len(en_keys)} canonical keys")
for code in sorted(stats):
    c, t = stats[code]
    flag = "OK" if c >= t else f"{c}/{t}"
    print(f"  {code}: {flag}")
